# Stage 1: Build the application
FROM public.ecr.aws/lambda/nodejs:20-x86_64 as development

WORKDIR /app

COPY tsconfig*.json ./
COPY package*.json ./

RUN npm ci

COPY src/ src/

RUN npm run build

# Stage 2: Create the production image
FROM public.ecr.aws/lambda/nodejs:20-x86_64 as production

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY --from=development /app/dist/ ./dist/

# Debug: List the contents of dist directory
RUN ls -la dist/

# Set the Lambda handler
CMD [ "/app/dist/lambda.handler" ]