name: Deploy Smart Wishlist API

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main

# These permissions are necessary for the workflow to authenticate with AWS
permissions:
  id-token: write
  contents: read

jobs:
  # --- First Job: Run Tests ---
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install server dependencies
        run: npm ci
        working-directory: ./server

      - name: Run linter
        run: npm run lint
        working-directory: ./server

      - name: Run tests
        run: npm test
        working-directory: ./server

  # --- Second Job: Deploy to AWS ---
  deploy:
    runs-on: ubuntu-latest
    needs: test # This job will only run if the 'test' job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::628316168607:role/GitHubAction-SmartWishlist-DeployRole
          aws-region: us-east-1 # Or the preferred region

      - name: Install infrastructure dependencies
        run: npm ci
        working-directory: ./infrastructure

      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never
        working-directory: ./infrastructure