name: Deploy Smart Wishlist

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write # Required for OIDC
  contents: read # Required to checkout the code

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install server dependencies
        run: cd server && npm ci

      - name: Run linter
        run: cd server && npm run lint

      - name: Run tests
        run: cd server && npm run test

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test # This job runs only after 'test' succeeds

    # These outputs are passed to the next job
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::628316168607:role/GitHubAction-SmartWishlist-DeployRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/smart-wishlist-api
          tags: |
            type=sha,prefix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server # Path to our Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy CDK Stack
    runs-on: ubuntu-latest
    needs: build-and-push # This job runs only after 'build-and-push' succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::628316168607:role/GitHubAction-SmartWishlist-DeployRole
          aws-region: us-east-1

      - name: Install infrastructure dependencies
        run: cd infrastructure && npm ci

      - name: Install AWS CDK globally
        run: npm install -g aws-cdk
      
      - name: Deploy CDK Stack
        run: |
          cd infrastructure
          cdk deploy --require-approval never --parameters imageTag=${{ needs.build-and-push.outputs.image_tag }}